{% set version = '0.1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-symphony
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/symphony_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/symphony/symphony_{{ version }}.tar.gz
  sha256: 8c69883459a418d8079811c40c7b6fbc1b3a3709f3e3bf642d500b20a082ed2d

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-matrix
    - r-rann
    - r-rcolorbrewer
    - r-rcpp
    - r-rcpparmadillo
    - r-class
    - r-data.table
    - r-dplyr
    - r-ggplot2
    - r-harmony
    - r-irlba
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-uwot
    - libblas
    - liblapack
  run:
    - r-base
    - {{ native }}gcc-libs           # [win]
    - {{ native }}libwinpthread-git  # [win]
    - r-matrix
    - r-rann
    - r-rcolorbrewer
    - r-rcpp
    - r-rcpparmadillo
    - r-class
    - r-data.table
    - r-dplyr
    - r-ggplot2
    - r-harmony
    - r-irlba
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-tibble
    - r-tidyr
    - r-uwot

test:
  commands:
    - $R -e "library('symphony')"           # [not win]
    - "\"%R%\" -e \"library('symphony')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=symphony
  license: GPL-3.0-or-later
  summary: Implements the Symphony single-cell reference building and query mapping algorithms
    and additional functions described in Kang et al <https://www.nature.com/articles/s41467-021-25957-x>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - janjagusch


# Package: symphony
# Title: Efficient and Precise Single-Cell Reference Atlas Mapping
# Version: 0.1.1
# Authors@R: c( person(given = "Joyce", family = "Kang", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-1962-1291"), email = "joyce_kang@hms.harvard.edu"), person("Ilya", "Korsunsky", email = "ilya.korsunsky@gmail.com", role = c("aut"), comment = c(ORCID = "0000-0003-4848-3948")), person("Soumya", "Raychaudhuri", role = c("aut"), comment = c(ORCID = "0000-0002-1901-8265")) )
# Description: Implements the Symphony single-cell reference building and query mapping algorithms and additional functions described in Kang et al <https://www.nature.com/articles/s41467-021-25957-x>.
# License: GPL (>= 3)
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.3
# Suggests: knitr, rmarkdown, testthat, ggthemes, ggrastr, ggrepel
# LinkingTo: Rcpp, RcppArmadillo
# Imports: methods, Rcpp, harmony, uwot, irlba, class, purrr, dplyr, ggplot2, stats, utils, magrittr, data.table, tibble, Matrix, tidyr, rlang, RColorBrewer, RANN
# VignetteBuilder: knitr
# Depends: R (>= 3.5)
# NeedsCompilation: yes
# Packaged: 2023-01-16 18:27:53 UTC; jbk37
# Author: Joyce Kang [aut, cre] (<https://orcid.org/0000-0002-1962-1291>), Ilya Korsunsky [aut] (<https://orcid.org/0000-0003-4848-3948>), Soumya Raychaudhuri [aut] (<https://orcid.org/0000-0002-1901-8265>)
# Maintainer: Joyce Kang <joyce_kang@hms.harvard.edu>
# Repository: CRAN
# Date/Publication: 2023-01-16 19:30:02 UTC
